{
  "swagger": "2.0",
  "info": {
    "title": "BPD IO Citizen API",
    "version": "v2",
    "description": "Api and Models"
  },
  "host": "prod.cstar.pagopa.it",
  "basePath": "/bpd/io/citizen/v2",
  "schemes": [
    "https"
  ],
  "paths": {
    "/": {
      "get": {
        "description": "find",
        "operationId": "findUsingGET",
        "summary": "find",
        "tags": [
          "Bonus Pagamenti Digitali Citizen Controller"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Auth Token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CitizenResource"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": ""
          }
        }
      },
      "delete": {
        "description": "delete",
        "operationId": "deleteUsingDELETE",
        "summary": "delete",
        "tags": [
          "Bonus Pagamenti Digitali Citizen Controller"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Auth Token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "patch": {
        "description": "updatePaymentMethod",
        "operationId": "updatePaymentMethodUsingPATCH",
        "summary": "updatePaymentMethod",
        "tags": [
          "Bonus Pagamenti Digitali Citizen Controller"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Auth Token",
            "required": true,
            "type": "string"
          },
          {
            "name": "citizenPatchDTO",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CitizenPatchDTO"
            },
            "description": "citizen"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/CitizenPatchResource"
            }
          },
          "400": {
            "description": ""
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": ""
          }
        }
      },
      "put": {
        "description": "enrollCitizenIO",
        "operationId": "enrollment",
        "summary": "enrollCitizenIO",
        "tags": [
          "Bonus Pagamenti Digitali enrollment Controller"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Auth Token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CitizenResource"
            }
          },
          "401": {
            "description": ""
          },
          "500": {
            "description": ""
          }
        }
      }
    },
    "/ranking": {
      "get": {
        "description": "findRanking",
        "operationId": "findRankingUsingGET",
        "summary": "findRanking",
        "tags": [
          "Bonus Pagamenti Digitali Citizen Controller"
        ],
        "parameters": [
          {
            "name": "awardPeriodId",
            "in": "query",
            "type": "string"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Auth Token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CitizenRankingMilestoneResourceArray"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": ""
          }
        }
      }
    },
    "/ranking/milestone": {
      "get": {
        "description": "findRankingMilestone",
        "operationId": "findRankingMilestoneUsingGET",
        "summary": "findRankingMilestone",
        "tags": [
          "Bonus Pagamenti Digitali Citizen Controller"
        ],
        "parameters": [
          {
            "name": "awardPeriodId",
            "in": "query",
            "description": "identificativo univoco del periodo di premiazione",
            "required": true,
            "type": "integer"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Auth Token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/CitizenRankingMilestoneResourceArray"
            }
          },
          "401": {
            "description": ""
          },
          "404": {
            "description": ""
          },
          "500": {
            "description": ""
          }
        }
      }
    }
  },
  "definitions": {
    "CitizenDTO": {
      "title": "CitizenDTO",
      "required": [
        "timestampTC"
      ],
      "type": "object",
      "properties": {
        "timestampTC": {
          "format": "date-time",
          "description": "timestamp dell'accettazione di T&C. FORMATO  ISO8601 yyyy-MM-ddTHH:mm:ss.SSSXXXXX",
          "type": "string"
        }
      }
    },
    "CitizenPatchDTO": {
      "title": "CitizenPatchDTO",
      "required": [
        "accountHolderCF",
        "accountHolderName",
        "accountHolderSurname",
        "payoffInstr",
        "payoffInstrType"
      ],
      "type": "object",
      "properties": {
        "accountHolderCF": {
          "description": "CF dell'intestatario dell'IBAN",
          "type": "string"
        },
        "accountHolderName": {
          "description": "Nome dell'intestatario dell'IBAN",
          "type": "string"
        },
        "accountHolderSurname": {
          "description": "Cognome dell'intestatario dell'IBAN",
          "type": "string"
        },
        "payoffInstr": {
          "description": "identificativo dello strumento di pagamento per la riscossione del premio",
          "type": "string"
        },
        "payoffInstrType": {
          "description": "tipologia di strumento di pagamento per la riscossione del premio",
          "enum": [
            "IBAN"
          ],
          "type": "string"
        }
      },
      "example": {
        "accountHolderCF": "string",
        "accountHolderName": "string",
        "accountHolderSurname": "string",
        "payoffInstr": "string",
        "payoffInstrType": "string"
      }
    },
    "CitizenPatchResource": {
      "title": "CitizenPatchResource",
      "required": [
        "validationStatus"
      ],
      "type": "object",
      "properties": {
        "validationStatus": {
          "description": "Stato di validazione a seguito della chiamata al servizio di checkIban.",
          "type": "string"
        }
      },
      "example": {
        "validationStatus": "string"
      }
    },
    "CitizenRankingResource": {
      "title": "CitizenRankingResource",
      "required": [
        "totalParticipants",
        "ranking",
        "maxTransactionNumber",
        "minTransactionNumber",
        "transactionNumber",
        "awardPeriodId"
      ],
      "type": "object",
      "properties": {
        "totalParticipants": {
          "format": "int64",
          "description": "numero totale di partecipanti al Bonus Pagamenti Digitali",
          "type": "integer"
        },
        "ranking": {
          "format": "int64",
          "description": "posizione della graduatoria riferita al periodo di premiazione corrente",
          "type": "integer"
        },
        "maxTransactionNumber": {
          "format": "int64",
          "description": "Numero massimo di transazioni effettuate dagli utenti che rientrano nel 'rimborso speciale'",
          "type": "integer"
        },
        "minTransactionNumber": {
          "format": "int64",
          "description": "Numero minimo di transazioni effettuate dagli utenti che rientrano nel 'rimborso speciale'",
          "type": "integer"
        },
        "transactionNumber": {
          "format": "int64",
          "description": "Numero di transazioni effettuate dallâ€™utente",
          "type": "integer"
        },
        "awardPeriodId": {
          "format": "int64",
          "description": "identificativo univoco del periodo di premiazione",
          "type": "integer"
        }
      },
      "example": {
        "totalParticipants": 0,
        "ranking": 0
      }
    },
    "TotalCashbackResource": {
      "title": "TotalCashbackResource",
      "required": [
        "totalCashback",
        "transactionNumber"
      ],
      "type": "object",
      "properties": {
        "totalCashback": {
          "description": "Cashback transazione, indicato con segno '-' in caso di storno",
          "type": "number"
        },
        "transactionNumber": {
          "format": "int64",
          "description": "Numero delle transazioni effettuate dall'utente",
          "type": "integer"
        }
      }
    },
    "CitizenResource": {
      "title": "CitizenResource",
      "required": [
        "enabled",
        "fiscalCode",
        "payoffInstr",
        "payoffInstrType",
        "timestampTC",
        "optInStatus"
      ],
      "type": "object",
      "properties": {
        "enabled": {
          "description": "stato dell'abilitazione al servizio da parte del citizen",
          "type": "boolean"
        },
        "fiscalCode": {
          "description": "id dell'utente, che corrisponde al codice fiscale",
          "type": "string"
        },
        "payoffInstr": {
          "description": "identificativo dello strumento di pagamento per la riscossione del premi",
          "type": "string"
        },
        "payoffInstrType": {
          "description": "tipologia di strumento di pagamento per la riscossione del premio",
          "type": "string"
        },
        "timestampTC": {
          "format": "date-time",
          "description": "timestamp dell'accettazione di T&C. FORMATO  ISO8601 yyyy-MM-ddTHH:mm:ss.SSSXXXXX",
          "type": "string"
        },
        "technicalAccount": {
          "description": "Label fissa tramite la quale si verifica la presenza di un conto tecnico. Quando tale campo sarÃ  valorizzato, il Client dovrÃ  mascherare lâ€™IBAN inviato nel campo payoffInstr",
          "type": "string"
        },
        "technicalAccountHolder": {
          "description": "Ragione sociale dellâ€™Issuer presso il quale Ã¨ stato aperto il conto. Esempio: CONTO TECNICO srl",
          "type": "string"
        },
        "issuerCardId": {
          "description": "Identificativo univoco dello strumento di pagamento rilasciato dall'issuer",
          "type": "string"
        },
        "optInStatus": {
          "enum": ["NOREQ","ACCEPTED","DENIED"],
          "type": "string",
          "description": "stato della richiesta utente di Opt-In per il mantenimento delle carte in AppIO"
        }
      },
      "example": {
        "enabled": false,
        "fiscalCode": "string",
        "payoffInstr": "string",
        "payoffInstrType": "string",
        "timestampTC": "string"
      }
    },
    "CitizenRankingMilestoneResourceArray": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/CitizenRankingMilestoneResource"
      },
      "example": [
        {
          "awardPeriodId": 0,
          "maxTransactionNumber": 0,
          "milestoneResource": {
            "cashbackNorm": "string",
            "idTrxMinTransactionNumber": "string",
            "idTrxPivot": "string",
            "maxCashback": "string",
            "totalCashback": "string"
          },
          "minTransactionNumber": 0,
          "ranking": 0,
          "totalParticipants": 0,
          "transactionNumber": 0
        }
      ]
    },
    "CitizenRankingResourceArray": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/CitizenRankingResource"
      },
      "example": [
        {
          "totalParticipants": 0,
          "ranking": 0,
          "maxTransactionNumber": 0,
          "minTransactionNumber": 0,
          "transactionNumber": 0,
          "awardPeriodId": 0
        }
      ]
    },
    "CitizenRankingMilestoneResource": {
      "title": "CitizenRankingMilestoneResource",
      "required": [
        "awardPeriodId",
        "maxTransactionNumber",
        "minTransactionNumber",
        "ranking",
        "totalParticipants",
        "transactionNumber"
      ],
      "type": "object",
      "properties": {
        "awardPeriodId": {
          "format": "int64",
          "description": "identificativo univoco del periodo di premiazione",
          "type": "integer"
        },
        "maxTransactionNumber": {
          "format": "int64",
          "description": "Numero massimo di transazioni effettuate dagli utenti che rientrano nel â€¢rimborso specialeâ€¢",
          "type": "integer"
        },
        "milestoneResource": {
          "$ref": "#/definitions/MilestoneResource"
        },
        "minTransactionNumber": {
          "format": "int64",
          "description": "Numero minimo di transazioni effettuate dagli utenti che rientrano nel â€¢rimborso specialeâ€¢",
          "type": "integer"
        },
        "ranking": {
          "format": "int64",
          "description": "posizione della graduatoria riferita al periodo di premiazione corrente",
          "type": "integer"
        },
        "totalParticipants": {
          "format": "int64",
          "description": "numero totale di partecipanti al Bonus Pagamenti Digitali",
          "type": "integer"
        },
        "transactionNumber": {
          "format": "int64",
          "description": "Numero di transazioni effettuate dallâ€¢utente",
          "type": "integer"
        }
      },
      "example": {
        "awardPeriodId": 0,
        "maxTransactionNumber": 0,
        "milestoneResource": {
          "cashbackNorm": "string",
          "idTrxMinTransactionNumber": "string",
          "idTrxPivot": "string",
          "maxCashback": "string",
          "totalCashback": "string"
        },
        "minTransactionNumber": 0,
        "ranking": 0,
        "totalParticipants": 0,
        "transactionNumber": 0
      }
    },
    "MilestoneResource": {
      "title": "MilestoneResource",
      "type": "object",
      "properties": {
        "cashbackNorm": {
          "type": "number"
        },
        "idTrxMinTransactionNumber": {
          "type": "string"
        },
        "idTrxPivot": {
          "type": "string"
        },
        "maxCashback": {
          "type": "number"
        },
        "totalCashback": {
          "type": "number"
        }
      },
      "example": {
        "cashbackNorm": "string",
        "idTrxMinTransactionNumber": "string",
        "idTrxPivot": "string",
        "maxCashback": "string",
        "totalCashback": "string"
      }
    }
  },
  "tags": [
    {
      "name": "Bonus Pagamenti Digitali Citizen Controller",
      "description": "Bpd Citizen Controller Impl"
    }
  ]
}