{
  "swagger": "2.0",
  "info": {
    "title": "BPD IO Winning Transactions API",
    "version": "v2",
    "description": "Api and Models"
  },
  "host": "prod.cstar.pagopa.it",
  "basePath": "/bpd/io/winning-transactions/v2",
  "schemes": [
    "https"
  ],
  "paths": {
    "/": {
      "get": {
        "description": "findWinningTransactions",
        "operationId": "findWinningTransactionsUsingGET",
        "summary": "findWinningTransactions",
        "tags": [
          "Bonus Pagamenti Digitali winning-transaction Controller"
        ],
        "parameters": [
          {
            "name": "hpan",
            "in": "query",
            "description": "id dello strumento di pagamento, che corrisponde all'hash del PAN (Primary Account Number) del metodo di pagamento",
            "type": "string"
          },
          {
            "name": "awardPeriodId",
            "in": "query",
            "description": "awardPeriodId",
            "required": true,
            "type": "integer"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Limite massimo di elementi contenuti nella pagina di risposta",
            "type": "integer"
          },
          {
            "name": "nextCursor",
            "in": "query",
            "description": "Id cursore da usare per la prossima richiesta per proseguire con la prossima pagina",
            "type": "integer"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WinningTransactionPageResource"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": ""
          }
        }
      }
    },
    "/total-cashback": {
      "get": {
        "description": "getTotalCashback",
        "operationId": "getTotalScoreUsingGET",
        "summary": "getTotalCashback",
        "tags": [
          "Bonus Pagamenti Digitali winning-transaction Controller"
        ],
        "parameters": [
          {
            "name": "awardPeriodId",
            "in": "query",
            "description": "awardPeriodId",
            "required": true,
            "type": "integer"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/TotalCashbackResource"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": ""
          }
        }
      }
    },
    "/countbyday": {
      "get": {
        "description": "getCountByDay",
        "operationId": "getCountByDayGET",
        "summary": "getCountByDay",
        "parameters": [
          {
            "name": "hpan",
            "in": "query",
            "description": "id dello strumento di pagamento, che corrisponde all'hash del PAN (Primary Account Number) del metodo di pagamento",
            "type": "string"
          },
          {
            "name": "awardPeriodId",
            "in": "query",
            "description": "awardPeriodId",
            "required": true,
            "type": "integer"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Bearer Token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/TrxCountByDayResourceArray"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": ""
          }
        }
      }
    }
  },
  "definitions": {
    "TotalCashbackResource": {
      "title": "TotalCashbackResource",
      "required": [
        "totalCashback",
        "transactionNumber"
      ],
      "type": "object",
      "properties": {
        "totalCashback": {
          "description": "Cashback transazione, indicato con segno '-' in caso di storno",
          "type": "number"
        },
        "transactionNumber": {
          "format": "int64",
          "description": "Numero delle transazioni effettuate dall'utente",
          "type": "integer"
        }
      },
      "example": {
        "totalCashback": 0.708740587556467,
        "transactionNumber": 0
      }
    },
    "TrxCountByDayResourceArray": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/TrxCountByDayResource"
      },
      "example": [
        {
          "count": "string",
          "trxDate": "string"
        }
      ]
    },
    "WinningTransactionMilestoneResource": {
      "title": "WinningTransactionMilestoneResource",
      "required": [
        "amount",
        "awardPeriodId",
        "cashback",
        "circuitType",
        "hashPan",
        "idTrx",
        "idTrxAcquirer",
        "idTrxIssuer",
        "trxDate"
      ],
      "type": "object",
      "properties": {
        "amount": {
          "description": "in centesimi di euro (es: 10• = 1000) ed in valore assoluto",
          "type": "number"
        },
        "awardPeriodId": {
          "format": "int64",
          "description": "identificativo univoco del periodo di premiazione",
          "type": "integer"
        },
        "cashback": {
          "description": "Cashback transazione, indicato con segno \"-\" in caso di storno",
          "type": "number"
        },
        "circuitType": {
          "description": "Circuito sul quale è stata effettuata la transazione",
          "type": "string"
        },
        "hashPan": {
          "description": "id dello strumento di pagamento, che corrisponde all'hash del PAN (Primary Account Number) del metodo di pagamento",
          "type": "string"
        },
        "idTrx": {
          "description": "Identificativo alfanumerico della transazione",
          "type": "string"
        },
        "idTrxAcquirer": {
          "description": "identificativo univoco della transazione a livello di Acquirer (all'interno di uno specifico periodo temporale, può coincidere per esempio con RRN+STAN)",
          "type": "string"
        },
        "idTrxIssuer": {
          "description": "codice autorizzativo rilasciato dall' Issuer (es: AuthCode)",
          "type": "string"
        },
        "trxDate": {
          "format": "date-time",
          "description": "timestamp dell'operazione di pagamento effettuata presso l'esercente",
          "type": "string"
        }
      },
      "example": {
        "amount": 0.600811258744409,
        "awardPeriodId": 0,
        "cashback": 0.8088633048680789,
        "circuitType": "string",
        "hashPan": "string",
        "idTrx": "string",
        "idTrxAcquirer": "string",
        "idTrxIssuer": "string",
        "trxDate": "string"
      }
    },
    "WinningTransactionResource": {
      "title": "WinningTransactionResource",
      "required": [
        "acquirerCode",
        "awardPeriodId",
        "correlationId",
        "hashPan",
        "idTrxAcquirer",
        "idTrxIssuer",
        "mcc",
        "operationType",
        "score",
        "trxDate"
      ],
      "type": "object",
      "properties": {
        "acquirerCode": {
          "description": "codice univoco rilasciato da pagoPa SpA",
          "type": "string"
        },
        "awardPeriodId": {
          "format": "int64",
          "description": "identificativo univoco del periodo di premiazione",
          "type": "integer"
        },
        "correlationId": {
          "description": "Identificativo di correlazione fra operazione di pagamento ed eventuale storno/reversa",
          "type": "string"
        },
        "hashPan": {
          "description": "id dello strumento di pagamento, che corrisponde all'hash del PAN (Primary Account Number) del metodo di pagamento",
          "type": "string"
        },
        "idTrxAcquirer": {
          "description": "identificativo univoco della transazione a livello di Acquirer (all'interno di uno specifico periodo temporale, puÃ² coincidere per esempio con RRN+STAN)",
          "type": "string"
        },
        "idTrxIssuer": {
          "description": "codice autorizzativo rilasciato dall' Issuer (es: AuthCode)",
          "type": "string"
        },
        "mcc": {
          "description": "Merchant Category Code",
          "type": "string"
        },
        "operationType": {
          "$ref": "#/definitions/OperationType"
        },
        "score": {
          "description": "punteggio della transazione",
          "type": "number"
        },
        "trxDate": {
          "format": "date-time",
          "description": "timestamp dell'operazione di pagamento effettuata presso l'esercente",
          "type": "string"
        }
      },
      "example": {
        "acquirerCode": "string",
        "awardPeriodId": 0,
        "correlationId": "string",
        "hashPan": "string",
        "idTrxAcquirer": "string",
        "idTrxIssuer": "string",
        "mcc": "string",
        "operationType": {
          "code": "string",
          "description": "string"
        },
        "score": 0.16729426629335253,
        "trxDate": "string"
      }
    },
    "OperationType": {
      "title": "OperationType",
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "example": {
        "code": "string",
        "description": "string"
      }
    },
    "WinningTransactionResourceArray": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/WinningTransactionResource"
      },
      "example": [
        {
          "acquirerCode": "string",
          "awardPeriodId": 0,
          "correlationId": "string",
          "hashPan": "string",
          "idTrxAcquirer": "string",
          "idTrxIssuer": "string",
          "mcc": "string",
          "operationType": {
            "code": "string",
            "description": "string"
          },
          "score": 0.6566477182521246,
          "trxDate": "string"
        }
      ]
    },
    "WinningTransactionPageResource": {
      "title": "WinningTransactionPage",
      "required": [
        "transactions"
      ],
      "type": "object",
      "properties": {
        "nextCursor": {
          "format": "int32",
          "description": "Id cursore da usare per la prossima richiesta per proseguire con la prossima pagina",
          "type": "integer"
        },
        "prevCursor": {
          "format": "int32",
          "description": "Id cursore da usare per la richiesta precedente per proseguire con la pagina precedente",
          "type": "integer"
        },
        "transactions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/WinningTransactionsOfTheDayResource"
          }
        }
      },
      "example": {
        "nextCursor": 0,
        "prevCursor": 0,
        "transactions": [
          {
            "date": "string",
            "transactions": [
              {
                "amount": 0.6673903446741356,
                "awardPeriodId": 0,
                "cashback": 0.52070866549666,
                "circuitType": "string",
                "hashPan": "string",
                "idTrx": "string",
                "idTrxAcquirer": "string",
                "idTrxIssuer": "string",
                "trxDate": "string"
              }
            ]
          }
        ]
      }
    },
    "TrxCountByDayResource": {
      "title": "TrxCountByDayResource",
      "type": "object",
      "required": ["count", "trxDate"],
      "properties": {
        "count": {
          "format": "int64",
          "description": "numero di transazioni presenti per data",
          "type": "integer"
        },
        "trxDate": {
          "format": "date",
          "description": "data di riferimento delle transazioni",
          "type": "string"
        }
      },
      "example": {
        "count": 0,
        "trxDate": "string"
      }
    },
    "WinningTransactionDTO": {
      "title": "WinningTransactionDTO",
      "required": [
        "acquirerCode",
        "acquirerId",
        "amount",
        "awardPeriodId",
        "bin",
        "correlationId",
        "hpan",
        "idTrxAcquirer",
        "idTrxIssuer",
        "mcc",
        "merchantId",
        "operationType",
        "score",
        "terminalId",
        "trxDate"
      ],
      "type": "object",
      "properties": {
        "acquirerCode": {
          "description": "codice univoco rilasciato da pagoPa SpA",
          "type": "string"
        },
        "acquirerId": {
          "description": "nel caso di transazione con carta rappresenta il valore omonimo veicolato nei tracciati dei circuiti internazionali",
          "type": "string"
        },
        "amount": {
          "description": "in centesimi di euro (es: 10 = 1000) ed in valore assoluto",
          "type": "number"
        },
        "amountCurrency": {
          "type": "string"
        },
        "awardPeriodId": {
          "format": "int64",
          "description": "identificativo univoco del periodo di premiazione",
          "type": "integer"
        },
        "bin": {
          "type": "string"
        },
        "circuitType": {
          "type": "string"
        },
        "correlationId": {
          "description": "Identificativo di correlazione fra operazione di pagamento ed eventuale storno/reversa",
          "type": "string"
        },
        "hpan": {
          "description": "identificativo univoco dello strumento di pagamento",
          "type": "string"
        },
        "idTrxAcquirer": {
          "description": "identificativo univoco della transazione a livello di Acquirer (all'interno di uno specifico periodo temporale, puÃ² coincidere per esempio con RRN+STAN)",
          "type": "string"
        },
        "idTrxIssuer": {
          "description": "codice autorizzativo rilasciato dall' Issuer (es: AuthCode)",
          "type": "string"
        },
        "mcc": {
          "description": "Merchant Category Code",
          "type": "string"
        },
        "mccDescription": {
          "type": "string"
        },
        "merchantId": {
          "description": "Identificativo univoco del negozio fisico presso l'Acquirer. serve ad identificare l'esercente e la categoria merceologica.",
          "type": "string"
        },
        "operationType": {
          "description": "tipologia operazione, la codifica Ã¨ la stessa utilizzata nel file standard csv",
          "type": "string"
        },
        "score": {
          "description": "punteggio della transazione",
          "type": "number"
        },
        "terminalId": {
          "description": "identificativo del terminale su cui è avvenuta la transazione",
          "type": "string"
        },
        "trxDate": {
          "format": "date-time",
          "description": "timestamp dell'operazione di pagamento effettuata presso l'esercente",
          "type": "string"
        }
      }
    },
    "WinningTransactionsOfTheDayResource": {
      "title": "WinningTransactionsOfTheDay",
      "description": "Oggetto che raggruppa le transazioni effettuate in una giornata",
      "required": [
        "date",
        "transactions"
      ],
      "type": "object",
      "properties": {
        "date": {
          "format": "date",
          "description": "La data del giorno di riferimento",
          "type": "string"
        },
        "transactions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/WinningTransactionMilestoneResource"
          }
        }
      },
      "example": {
        "date": "string",
        "transactions": [
          {
            "amount": 0.008187017182033518,
            "awardPeriodId": 0,
            "cashback": 0.8299686893360614,
            "circuitType": "string",
            "hashPan": "string",
            "idTrx": "string",
            "idTrxAcquirer": "string",
            "idTrxIssuer": "string",
            "trxDate": "string"
          }
        ]
      }
    }
  },
  "tags": []
}